"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_expression_kind import EdmExpressionKind


class TestEdmExpressionKind(unittest.TestCase):
    """EdmExpressionKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdmExpressionKind(self):
        """Test EdmExpressionKind"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdmExpressionKind()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
