"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.grid_view_column import GridViewColumn
globals()['GridViewColumn'] = GridViewColumn
from okclient.model.grid_view_configuration import GridViewConfiguration


class TestGridViewConfiguration(unittest.TestCase):
    """GridViewConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridViewConfiguration(self):
        """Test GridViewConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GridViewConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
