# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import okclient
from okclient.api.graphviz_dot_api import GraphvizDotApi  # noqa: E501


class TestGraphvizDotApi(unittest.TestCase):
    """GraphvizDotApi unit test stubs"""

    def setUp(self):
        self.api = GraphvizDotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_graphviz_dot_layer_centric(self):
        """Test case for graphviz_dot_layer_centric

        """
        pass

    def test_graphviz_dot_trait_centric(self):
        """Test case for graphviz_dot_trait_centric

        """
        pass


if __name__ == '__main__':
    unittest.main()
