"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_schema_element_kind import EdmSchemaElementKind
from okclient.model.i_edm_entity_container_element import IEdmEntityContainerElement
globals()['EdmSchemaElementKind'] = EdmSchemaElementKind
globals()['IEdmEntityContainerElement'] = IEdmEntityContainerElement
from okclient.model.i_edm_entity_container import IEdmEntityContainer


class TestIEdmEntityContainer(unittest.TestCase):
    """IEdmEntityContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmEntityContainer(self):
        """Test IEdmEntityContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmEntityContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
