"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.i_edm_entity_container import IEdmEntityContainer
from okclient.model.i_edm_schema_element import IEdmSchemaElement
from okclient.model.i_edm_vocabulary_annotation import IEdmVocabularyAnnotation
globals()['IEdmEntityContainer'] = IEdmEntityContainer
globals()['IEdmSchemaElement'] = IEdmSchemaElement
globals()['IEdmVocabularyAnnotation'] = IEdmVocabularyAnnotation
from okclient.model.i_edm_model import IEdmModel


class TestIEdmModel(unittest.TestCase):
    """IEdmModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmModel(self):
        """Test IEdmModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
