"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.generic_inbound_attribute import GenericInboundAttribute
from okclient.model.generic_inbound_ciid_method import GenericInboundCIIdMethod
from okclient.model.no_found_target_ci_handling import NoFoundTargetCIHandling
from okclient.model.same_target_ci_handling import SameTargetCIHandling
from okclient.model.same_temp_id_handling import SameTempIDHandling
globals()['GenericInboundAttribute'] = GenericInboundAttribute
globals()['GenericInboundCIIdMethod'] = GenericInboundCIIdMethod
globals()['NoFoundTargetCIHandling'] = NoFoundTargetCIHandling
globals()['SameTargetCIHandling'] = SameTargetCIHandling
globals()['SameTempIDHandling'] = SameTempIDHandling
from okclient.model.generic_inbound_ci import GenericInboundCI


class TestGenericInboundCI(unittest.TestCase):
    """GenericInboundCI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericInboundCI(self):
        """Test GenericInboundCI"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericInboundCI()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
