# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import okclient
from okclient.api.ok_plugin_insight_discovery_ingest_api import OKPluginInsightDiscoveryIngestApi  # noqa: E501
from okclient import configuration, schemas, api_client

from . import ApiTestMixin


class TestOKPluginInsightDiscoveryIngestApi(ApiTestMixin, unittest.TestCase):
    """OKPluginInsightDiscoveryIngestApi unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = OKPluginInsightDiscoveryIngestApi(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_ingest_file_ingest(self):
        """Test case for ingest_file_ingest

        """
        from okclient.api.ok_plugin_insight_discovery_ingest_api_endpoints import ingest_file_ingest as endpoint_module
        response_status = 200
        response_body = ''


if __name__ == '__main__':
    unittest.main()
