"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.attribute_value_image_api import AttributeValueImageApi  # noqa: E501


class TestAttributeValueImageApi(unittest.TestCase):
    """AttributeValueImageApi unit test stubs"""

    def setUp(self):
        self.api = AttributeValueImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attribute_value_image_get(self):
        """Test case for attribute_value_image_get

        """
        pass

    def test_attribute_value_image_post(self):
        """Test case for attribute_value_image_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
