"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.ansible_inventory_scan_ingest_api import AnsibleInventoryScanIngestApi  # noqa: E501


class TestAnsibleInventoryScanIngestApi(unittest.TestCase):
    """AnsibleInventoryScanIngestApi unit test stubs"""

    def setUp(self):
        self.api = AnsibleInventoryScanIngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ansible_inventory_scan_ingest_ingest_ansible_inventory_scan(self):
        """Test case for ansible_inventory_scan_ingest_ingest_ansible_inventory_scan

        """
        pass


if __name__ == '__main__':
    unittest.main()
