"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.ok_plugin_generic_json_ingest_api import OKPluginGenericJSONIngestApi  # noqa: E501


class TestOKPluginGenericJSONIngestApi(unittest.TestCase):
    """OKPluginGenericJSONIngestApi unit test stubs"""

    def setUp(self):
        self.api = OKPluginGenericJSONIngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_context(self):
        """Test case for add_new_context

        """
        pass

    def test_get_all_contexts(self):
        """Test case for get_all_contexts

        """
        pass

    def test_get_context_by_name(self):
        """Test case for get_context_by_name

        """
        pass

    def test_ingest(self):
        """Test case for ingest

        """
        pass

    def test_remove_context(self):
        """Test case for remove_context

        """
        pass


if __name__ == '__main__':
    unittest.main()
