# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import okclient
from okclient.api.ok_plugin_generic_json_ingest_api import OKPluginGenericJSONIngestApi  # noqa: E501


class TestOKPluginGenericJSONIngestApi(unittest.TestCase):
    """OKPluginGenericJSONIngestApi unit test stubs"""

    def setUp(self):
        self.api = OKPluginGenericJSONIngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_manage_context_get_all_contexts(self):
        """Test case for manage_context_get_all_contexts

        """
        pass

    def test_manage_context_get_context(self):
        """Test case for manage_context_get_context

        """
        pass

    def test_manage_context_remove_context(self):
        """Test case for manage_context_remove_context

        """
        pass

    def test_manage_context_upsert_context(self):
        """Test case for manage_context_upsert_context

        """
        pass

    def test_passive_data_ingest(self):
        """Test case for passive_data_ingest

        """
        pass

    def test_passive_files_ingest(self):
        """Test case for passive_files_ingest

        """
        pass


if __name__ == '__main__':
    unittest.main()
