"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_schema_element_kind import EdmSchemaElementKind


class TestEdmSchemaElementKind(unittest.TestCase):
    """EdmSchemaElementKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdmSchemaElementKind(self):
        """Test EdmSchemaElementKind"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdmSchemaElementKind()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
