"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.usage_stats_api import UsageStatsApi  # noqa: E501


class TestUsageStatsApi(unittest.TestCase):
    """UsageStatsApi unit test stubs"""

    def setUp(self):
        self.api = UsageStatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_usage_stats_fetch(self):
        """Test case for usage_stats_fetch

        """
        pass


if __name__ == '__main__':
    unittest.main()
