"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.ci_search_api import CISearchApi  # noqa: E501


class TestCISearchApi(unittest.TestCase):
    """CISearchApi unit test stubs"""

    def setUp(self):
        self.api = CISearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_cis_by_traits(self):
        """Test case for search_cis_by_traits

        """
        pass


if __name__ == '__main__':
    unittest.main()
