"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.attribute_value_type import AttributeValueType
globals()['AttributeValueType'] = AttributeValueType
from okclient.model.i_attribute_value import IAttributeValue


class TestIAttributeValue(unittest.TestCase):
    """IAttributeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIAttributeValue(self):
        """Test IAttributeValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IAttributeValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
