"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.o_data_type_annotation import ODataTypeAnnotation
globals()['ODataTypeAnnotation'] = ODataTypeAnnotation
from okclient.model.o_data_function_import_info import ODataFunctionImportInfo


class TestODataFunctionImportInfo(unittest.TestCase):
    """ODataFunctionImportInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataFunctionImportInfo(self):
        """Test ODataFunctionImportInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ODataFunctionImportInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
