"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.i_load_config import ILoadConfig


class TestILoadConfig(unittest.TestCase):
    """ILoadConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testILoadConfig(self):
        """Test ILoadConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ILoadConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
