"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_type_kind import EdmTypeKind
globals()['EdmTypeKind'] = EdmTypeKind
from okclient.model.i_edm_type import IEdmType


class TestIEdmType(unittest.TestCase):
    """IEdmType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmType(self):
        """Test IEdmType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
