"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.ok_plugin_insight_discovery_ingest_api import OKPluginInsightDiscoveryIngestApi  # noqa: E501


class TestOKPluginInsightDiscoveryIngestApi(unittest.TestCase):
    """OKPluginInsightDiscoveryIngestApi unit test stubs"""

    def setUp(self):
        self.api = OKPluginInsightDiscoveryIngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ingest_file_ingest(self):
        """Test case for ingest_file_ingest

        """
        pass


if __name__ == '__main__':
    unittest.main()
