# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import okclient
from okclient.api.usage_stats_api import UsageStatsApi  # noqa: E501
from okclient import configuration, schemas, api_client

from . import ApiTestMixin


class TestUsageStatsApi(ApiTestMixin, unittest.TestCase):
    """UsageStatsApi unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = UsageStatsApi(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_usage_stats_fetch(self):
        """Test case for usage_stats_fetch

        """
        from okclient.api.usage_stats_api_endpoints import usage_stats_fetch as endpoint_module
        response_status = 200
        response_body = ''
        pass


if __name__ == '__main__':
    unittest.main()
