"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.inbound_id_method_by_data import InboundIDMethodByData


class TestInboundIDMethodByData(unittest.TestCase):
    """InboundIDMethodByData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInboundIDMethodByData(self):
        """Test InboundIDMethodByData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InboundIDMethodByData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
