"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.grid_view_configuration import GridViewConfiguration
globals()['GridViewConfiguration'] = GridViewConfiguration
from okclient.model.edit_context_request import EditContextRequest


class TestEditContextRequest(unittest.TestCase):
    """EditContextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditContextRequest(self):
        """Test EditContextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditContextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
