"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.inbound_id_method_by_attribute import InboundIDMethodByAttribute
from okclient.model.inbound_id_method_by_by_union import InboundIDMethodByByUnion
from okclient.model.inbound_id_method_by_data import InboundIDMethodByData
from okclient.model.inbound_id_method_by_intersect import InboundIDMethodByIntersect
from okclient.model.inbound_id_method_by_related_temp_id import InboundIDMethodByRelatedTempID
from okclient.model.inbound_id_method_by_temporary_ciid import InboundIDMethodByTemporaryCIID
globals()['InboundIDMethodByAttribute'] = InboundIDMethodByAttribute
globals()['InboundIDMethodByByUnion'] = InboundIDMethodByByUnion
globals()['InboundIDMethodByData'] = InboundIDMethodByData
globals()['InboundIDMethodByIntersect'] = InboundIDMethodByIntersect
globals()['InboundIDMethodByRelatedTempID'] = InboundIDMethodByRelatedTempID
globals()['InboundIDMethodByTemporaryCIID'] = InboundIDMethodByTemporaryCIID
from okclient.model.abstract_inbound_id_method import AbstractInboundIDMethod


class TestAbstractInboundIDMethod(unittest.TestCase):
    """AbstractInboundIDMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAbstractInboundIDMethod(self):
        """Test AbstractInboundIDMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AbstractInboundIDMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
