"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.sparse_row import SparseRow
globals()['SparseRow'] = SparseRow
from okclient.model.change_data_request import ChangeDataRequest


class TestChangeDataRequest(unittest.TestCase):
    """ChangeDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeDataRequest(self):
        """Test ChangeDataRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeDataRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
