"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.ci_api import CIApi  # noqa: E501


class TestCIApi(unittest.TestCase):
    """CIApi unit test stubs"""

    def setUp(self):
        self.api = CIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_ciids(self):
        """Test case for get_all_ciids

        list of all CI-IDs  # noqa: E501
        """
        pass

    def test_get_ciby_id(self):
        """Test case for get_ciby_id

        single CI by CI-ID  # noqa: E501
        """
        pass

    def test_get_cis_by_id(self):
        """Test case for get_cis_by_id

        multiple CIs by CI-ID  !Watch out for the query URL getting too long because of a lot of CIIDs!  TODO: consider using POST  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
