# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import okclient
from okclient.api.import_export_layer_api import ImportExportLayerApi  # noqa: E501
from okclient import configuration, schemas, api_client

from . import ApiTestMixin


class TestImportExportLayerApi(ApiTestMixin, unittest.TestCase):
    """ImportExportLayerApi unit test stubs"""
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = ImportExportLayerApi(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_import_export_layer_export_layer(self):
        """Test case for import_export_layer_export_layer

        """
        from okclient.api.import_export_layer_api_endpoints import import_export_layer_export_layer as endpoint_module
        response_status = 200
        response_body = ''
        pass

    def test_import_export_layer_import_layer(self):
        """Test case for import_export_layer_import_layer

        """
        from okclient.api.import_export_layer_api_endpoints import import_export_layer_import_layer as endpoint_module
        response_status = 200
        response_body = ''


if __name__ == '__main__':
    unittest.main()
