"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.metadata_api import MetadataApi  # noqa: E501


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metadata_get_metadata(self):
        """Test case for metadata_get_metadata

        """
        pass

    def test_metadata_get_service_document(self):
        """Test case for metadata_get_service_document

        """
        pass


if __name__ == '__main__':
    unittest.main()
