"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.attribute_value_dto import AttributeValueDTO
globals()['AttributeValueDTO'] = AttributeValueDTO
from okclient.model.fragment_dto import FragmentDTO


class TestFragmentDTO(unittest.TestCase):
    """FragmentDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFragmentDTO(self):
        """Test FragmentDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FragmentDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
