"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.o_data_entity_set_info import ODataEntitySetInfo
from okclient.model.o_data_function_import_info import ODataFunctionImportInfo
from okclient.model.o_data_singleton_info import ODataSingletonInfo
from okclient.model.o_data_type_annotation import ODataTypeAnnotation
globals()['ODataEntitySetInfo'] = ODataEntitySetInfo
globals()['ODataFunctionImportInfo'] = ODataFunctionImportInfo
globals()['ODataSingletonInfo'] = ODataSingletonInfo
globals()['ODataTypeAnnotation'] = ODataTypeAnnotation
from okclient.model.o_data_service_document import ODataServiceDocument


class TestODataServiceDocument(unittest.TestCase):
    """ODataServiceDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataServiceDocument(self):
        """Test ODataServiceDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ODataServiceDocument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
