"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.graph_ql_api import GraphQLApi  # noqa: E501


class TestGraphQLApi(unittest.TestCase):
    """GraphQLApi unit test stubs"""

    def setUp(self):
        self.api = GraphQLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_graph_ql_debug(self):
        """Test case for graph_ql_debug

        """
        pass

    def test_graph_ql_get(self):
        """Test case for graph_ql_get

        """
        pass

    def test_graph_ql_index(self):
        """Test case for graph_ql_index

        """
        pass


if __name__ == '__main__':
    unittest.main()
