"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.ansible_inventory_scan_dto import AnsibleInventoryScanDTO


class TestAnsibleInventoryScanDTO(unittest.TestCase):
    """AnsibleInventoryScanDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnsibleInventoryScanDTO(self):
        """Test AnsibleInventoryScanDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnsibleInventoryScanDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
