"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_schema_element_kind import EdmSchemaElementKind
from okclient.model.i_edm_type_reference import IEdmTypeReference
globals()['EdmSchemaElementKind'] = EdmSchemaElementKind
globals()['IEdmTypeReference'] = IEdmTypeReference
from okclient.model.i_edm_term import IEdmTerm


class TestIEdmTerm(unittest.TestCase):
    """IEdmTerm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmTerm(self):
        """Test IEdmTerm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmTerm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
