"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.grid_view_api import GridViewApi  # noqa: E501


class TestGridViewApi(unittest.TestCase):
    """GridViewApi unit test stubs"""

    def setUp(self):
        self.api = GridViewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_context(self):
        """Test case for add_context

        Adds new context  # noqa: E501
        """
        pass

    def test_change_data(self):
        """Test case for change_data

        Saves grid view row changes and returns change results  # noqa: E501
        """
        pass

    def test_delete_context(self):
        """Test case for delete_context

        Deletes specific context  # noqa: E501
        """
        pass

    def test_edit_context(self):
        """Test case for edit_context

        Edits specific context  # noqa: E501
        """
        pass

    def test_get_context(self):
        """Test case for get_context

        Returns a single context in full  # noqa: E501
        """
        pass

    def test_get_contexts(self):
        """Test case for get_contexts

        Returns a list of contexts for grid view.  # noqa: E501
        """
        pass

    def test_get_data(self):
        """Test case for get_data

        Returns grid view data for specific context  # noqa: E501
        """
        pass

    def test_get_schema(self):
        """Test case for get_schema

        Returns grid view schema for specific context  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
