"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_container_element_kind import EdmContainerElementKind
from okclient.model.i_edm_entity_container import IEdmEntityContainer
globals()['EdmContainerElementKind'] = EdmContainerElementKind
globals()['IEdmEntityContainer'] = IEdmEntityContainer
from okclient.model.i_edm_entity_container_element import IEdmEntityContainerElement


class TestIEdmEntityContainerElement(unittest.TestCase):
    """IEdmEntityContainerElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmEntityContainerElement(self):
        """Test IEdmEntityContainerElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmEntityContainerElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
