# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import okclient
from okclient.api.auth_redirect_api import AuthRedirectApi  # noqa: E501


class TestAuthRedirectApi(unittest.TestCase):
    """AuthRedirectApi unit test stubs"""

    def setUp(self):
        self.api = AuthRedirectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_redirect_index(self):
        """Test case for auth_redirect_index

        """
        pass


if __name__ == '__main__':
    unittest.main()
