"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.grid_view_configuration import GridViewConfiguration
globals()['GridViewConfiguration'] = GridViewConfiguration
from okclient.model.add_context_request import AddContextRequest


class TestAddContextRequest(unittest.TestCase):
    """AddContextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddContextRequest(self):
        """Test AddContextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddContextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
