"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import okclient
from okclient.api.active_directory_xml_ingest_api import ActiveDirectoryXMLIngestApi  # noqa: E501


class TestActiveDirectoryXMLIngestApi(unittest.TestCase):
    """ActiveDirectoryXMLIngestApi unit test stubs"""

    def setUp(self):
        self.api = ActiveDirectoryXMLIngestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ingest_xml(self):
        """Test case for ingest_xml

        """
        pass


if __name__ == '__main__':
    unittest.main()
