"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.change_data_cell import ChangeDataCell
globals()['ChangeDataCell'] = ChangeDataCell
from okclient.model.sparse_row import SparseRow


class TestSparseRow(unittest.TestCase):
    """SparseRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSparseRow(self):
        """Test SparseRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SparseRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
