"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.fragment_dto import FragmentDTO
globals()['FragmentDTO'] = FragmentDTO
from okclient.model.bulk_ci_attribute_layer_scope_dto import BulkCIAttributeLayerScopeDTO


class TestBulkCIAttributeLayerScopeDTO(unittest.TestCase):
    """BulkCIAttributeLayerScopeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkCIAttributeLayerScopeDTO(self):
        """Test BulkCIAttributeLayerScopeDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BulkCIAttributeLayerScopeDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
