"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.edm_schema_element_kind import EdmSchemaElementKind
globals()['EdmSchemaElementKind'] = EdmSchemaElementKind
from okclient.model.i_edm_schema_element import IEdmSchemaElement


class TestIEdmSchemaElement(unittest.TestCase):
    """IEdmSchemaElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIEdmSchemaElement(self):
        """Test IEdmSchemaElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IEdmSchemaElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
