"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import okclient
from okclient.model.attribute_state import AttributeState
from okclient.model.attribute_value_dto import AttributeValueDTO
globals()['AttributeState'] = AttributeState
globals()['AttributeValueDTO'] = AttributeValueDTO
from okclient.model.ci_attribute_dto import CIAttributeDTO


class TestCIAttributeDTO(unittest.TestCase):
    """CIAttributeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCIAttributeDTO(self):
        """Test CIAttributeDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CIAttributeDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
