# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import re  # noqa: F401
import sys  # noqa: F401
import typing
import urllib3
import functools  # noqa: F401
from urllib3._collections import HTTPHeaderDict

from okclient import api_client, exceptions
import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)

# path params
IdSchema = StrSchema
VersionSchema = StrSchema
RequestRequiredPathParams = typing.TypedDict(
    'RequestRequiredPathParams',
    {
        'id': IdSchema,
        'version': VersionSchema,
    }
)
RequestOptionalPathParams = typing.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_id = api_client.PathParameter(
    name="id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IdSchema,
    required=True,
)
request_path_version = api_client.PathParameter(
    name="version",
    style=api_client.ParameterStyle.SIMPLE,
    schema=VersionSchema,
    required=True,
)
_path = '/api/v{version}/ingest/genericJSON/manage/context/{id}'
_method = 'GET'
_auth = [
    'oauth2',
    'oauth2',
]


class SchemaFor200ResponseBodyApplicationJson(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJson':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationXml(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationXml':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatafull(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatafull':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataMetadatanone(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataMetadatanone':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyTextPlain(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyTextPlain':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyApplicationOctetStream(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyApplicationOctetStream':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class SchemaFor200ResponseBodyTextJson(
    DictSchema
):
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'SchemaFor200ResponseBodyTextJson':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor200ResponseBodyApplicationJson,
        SchemaFor200ResponseBodyApplicationXml,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafull,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanone,
        SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse,
        SchemaFor200ResponseBodyTextPlain,
        SchemaFor200ResponseBodyApplicationOctetStream,
        SchemaFor200ResponseBodyTextJson,
    ]
    headers: Unset = unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationXml),
        'application/json;odata.metadata=minimal;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue),
        'application/json;odata.metadata=minimal;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse),
        'application/json;odata.metadata=minimal': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal),
        'application/json;odata.metadata=full;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue),
        'application/json;odata.metadata=full;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse),
        'application/json;odata.metadata=full': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafull),
        'application/json;odata.metadata=none;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue),
        'application/json;odata.metadata=none;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse),
        'application/json;odata.metadata=none': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanone),
        'application/json;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue),
        'application/json;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse),
        'text/plain': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextPlain),
        'application/octet-stream': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationOctetStream),
        'text/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
    'application/xml',
    'application/json;odata.metadata=minimal;odata.streaming=true',
    'application/json;odata.metadata=minimal;odata.streaming=false',
    'application/json;odata.metadata=minimal',
    'application/json;odata.metadata=full;odata.streaming=true',
    'application/json;odata.metadata=full;odata.streaming=false',
    'application/json;odata.metadata=full',
    'application/json;odata.metadata=none;odata.streaming=true',
    'application/json;odata.metadata=none;odata.streaming=false',
    'application/json;odata.metadata=none',
    'application/json;odata.streaming=true',
    'application/json;odata.streaming=false',
    'text/plain',
    'application/octet-stream',
    'text/json',
)


class ManageContextGetContext(api_client.Api):

    def manage_context_get_context(
        self: api_client.Api,
        path_params: RequestPathParams = frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs(RequestPathParams, path_params)
        used_path = _path

        _path_params = {}
        for parameter in (
            request_path_id,
            request_path_version,
        ):
            parameter_data = path_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)

        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        response = self.api_client.call_api(
            resource_path=used_path,
            method=_method,
            headers=_headers,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response
