"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from okclient.api_client import ApiClient, Endpoint as _Endpoint
from okclient.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from okclient.model.bulk_ci_attribute_layer_scope_dto import BulkCIAttributeLayerScopeDTO
from okclient.model.ci_attribute_dto import CIAttributeDTO


class AttributeApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __bulk_replace_attributes_in_layer(
            self,
            version,
            bulk_ci_attribute_layer_scope_dto,
            **kwargs
        ):
            """bulk replace all attributes in specified layer  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.bulk_replace_attributes_in_layer(version, bulk_ci_attribute_layer_scope_dto, async_req=True)
            >>> result = thread.get()

            Args:
                version (str):
                bulk_ci_attribute_layer_scope_dto (BulkCIAttributeLayerScopeDTO):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['version'] = \
                version
            kwargs['bulk_ci_attribute_layer_scope_dto'] = \
                bulk_ci_attribute_layer_scope_dto
            return self.call_with_http_info(**kwargs)

        self.bulk_replace_attributes_in_layer = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Attribute/bulkReplaceAttributesInLayer',
                'operation_id': 'bulk_replace_attributes_in_layer',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'version',
                    'bulk_ci_attribute_layer_scope_dto',
                ],
                'required': [
                    'version',
                    'bulk_ci_attribute_layer_scope_dto',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'version':
                        (str,),
                    'bulk_ci_attribute_layer_scope_dto':
                        (BulkCIAttributeLayerScopeDTO,),
                },
                'attribute_map': {
                    'version': 'version',
                },
                'location_map': {
                    'version': 'path',
                    'bulk_ci_attribute_layer_scope_dto': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'application/json-patch+json',
                    'text/json',
                    'application/*+json'
                ]
            },
            api_client=api_client,
            callable=__bulk_replace_attributes_in_layer
        )

        def __find_merged_attributes_by_name(
            self,
            regex,
            layer_ids,
            version,
            **kwargs
        ):
            """find_merged_attributes_by_name  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.find_merged_attributes_by_name(regex, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                regex (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                ciids ([str]): [optional]
                at_time (datetime): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [CIAttributeDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['regex'] = \
                regex
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.find_merged_attributes_by_name = _Endpoint(
            settings={
                'response_type': ([CIAttributeDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Attribute/findMergedAttributesByName',
                'operation_id': 'find_merged_attributes_by_name',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'regex',
                    'layer_ids',
                    'version',
                    'ciids',
                    'at_time',
                ],
                'required': [
                    'regex',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'regex':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'ciids':
                        ([str],),
                    'at_time':
                        (datetime,),
                },
                'attribute_map': {
                    'regex': 'regex',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'ciids': 'ciids',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'regex': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'ciids': 'query',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                    'ciids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__find_merged_attributes_by_name
        )

        def __get_merged_attribute(
            self,
            ciid,
            name,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_attribute  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_attribute(ciid, name, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                ciid (str):
                name (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                CIAttributeDTO
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['ciid'] = \
                ciid
            kwargs['name'] = \
                name
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_attribute = _Endpoint(
            settings={
                'response_type': (CIAttributeDTO,),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Attribute/getMergedAttribute',
                'operation_id': 'get_merged_attribute',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'ciid',
                    'name',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'ciid',
                    'name',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'ciid':
                        (str,),
                    'name':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime,),
                },
                'attribute_map': {
                    'ciid': 'ciid',
                    'name': 'name',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'ciid': 'query',
                    'name': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_attribute
        )

        def __get_merged_attributes(
            self,
            ciids,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_attributes  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_attributes(ciids, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                ciids ([str]):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [CIAttributeDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['ciids'] = \
                ciids
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_attributes = _Endpoint(
            settings={
                'response_type': ([CIAttributeDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Attribute/getMergedAttributes',
                'operation_id': 'get_merged_attributes',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'ciids',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'ciids',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'ciids':
                        ([str],),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime,),
                },
                'attribute_map': {
                    'ciids': 'ciids',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'ciids': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'ciids': 'multi',
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_attributes
        )

        def __get_merged_attributes_with_name(
            self,
            name,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_attributes_with_name  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_attributes_with_name(name, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                name (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [CIAttributeDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['name'] = \
                name
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_attributes_with_name = _Endpoint(
            settings={
                'response_type': ([CIAttributeDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Attribute/getMergedAttributesWithName',
                'operation_id': 'get_merged_attributes_with_name',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'name',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'name',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'name':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime,),
                },
                'attribute_map': {
                    'name': 'name',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'name': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_attributes_with_name
        )
