# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from okclient.api_client import ApiClient
from okclient.api.auth_redirect_api_endpoints.auth_redirect_index import AuthRedirectIndex


class AuthRedirectApi(
    AuthRedirectIndex,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
