# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from okclient.api_client import ApiClient
from okclient.api.graph_ql_api_endpoints.graph_ql_debug import GraphQlDebug
from okclient.api.graph_ql_api_endpoints.graph_ql_get import GraphQlGet
from okclient.api.graph_ql_api_endpoints.graph_ql_index import GraphQlIndex


class GraphQLApi(
    GraphQlDebug,
    GraphQlGet,
    GraphQlIndex,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
