# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from okclient.api_client import ApiClient
from okclient.api.metadata_api_endpoints.metadata_get_metadata import MetadataGetMetadata
from okclient.api.metadata_api_endpoints.metadata_get_service_document import MetadataGetServiceDocument


class MetadataApi(
    MetadataGetMetadata,
    MetadataGetServiceDocument,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
