# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from okclient.api_client import ApiClient
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.manage_context_get_all_contexts import ManageContextGetAllContexts
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.manage_context_get_context import ManageContextGetContext
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.manage_context_remove_context import ManageContextRemoveContext
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.manage_context_upsert_context import ManageContextUpsertContext
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.passive_data_ingest import PassiveDataIngest
from okclient.api.ok_plugin_generic_json_ingest_api_endpoints.passive_files_ingest import PassiveFilesIngest


class OKPluginGenericJSONIngestApi(
    ManageContextGetAllContexts,
    ManageContextGetContext,
    ManageContextRemoveContext,
    ManageContextUpsertContext,
    PassiveDataIngest,
    PassiveFilesIngest,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
