"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from okclient.api_client import ApiClient, Endpoint as _Endpoint
from okclient.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from okclient.model.relation_dto import RelationDTO


class RelationApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __get_all_merged_relations(
            self,
            layer_ids,
            version,
            **kwargs
        ):
            """get_all_merged_relations  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_all_merged_relations(layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime, none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_all_merged_relations = _Endpoint(
            settings={
                'response_type': ([RelationDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Relation/getAllMergedRelations',
                'operation_id': 'get_all_merged_relations',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                    'at_time',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime, none_type,),
                },
                'attribute_map': {
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_all_merged_relations
        )

        def __get_merged_relation(
            self,
            from_ciid,
            to_ciid,
            predicate_id,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_relation  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_relation(from_ciid, to_ciid, predicate_id, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                from_ciid (str):
                to_ciid (str):
                predicate_id (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime, none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RelationDTO
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['from_ciid'] = \
                from_ciid
            kwargs['to_ciid'] = \
                to_ciid
            kwargs['predicate_id'] = \
                predicate_id
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_relation = _Endpoint(
            settings={
                'response_type': (RelationDTO,),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Relation/getMergedRelation',
                'operation_id': 'get_merged_relation',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'from_ciid',
                    'to_ciid',
                    'predicate_id',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'from_ciid',
                    'to_ciid',
                    'predicate_id',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                    'at_time',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'from_ciid':
                        (str,),
                    'to_ciid':
                        (str,),
                    'predicate_id':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime, none_type,),
                },
                'attribute_map': {
                    'from_ciid': 'fromCIID',
                    'to_ciid': 'toCIID',
                    'predicate_id': 'predicateID',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'from_ciid': 'query',
                    'to_ciid': 'query',
                    'predicate_id': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_relation
        )

        def __get_merged_relations_from_or_to_ci(
            self,
            ciid,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_relations_from_or_to_ci  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_relations_from_or_to_ci(ciid, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                ciid (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime, none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['ciid'] = \
                ciid
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_relations_from_or_to_ci = _Endpoint(
            settings={
                'response_type': ([RelationDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Relation/getMergedRelationsFromOrToCI',
                'operation_id': 'get_merged_relations_from_or_to_ci',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'ciid',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'ciid',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                    'at_time',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'ciid':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime, none_type,),
                },
                'attribute_map': {
                    'ciid': 'ciid',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'ciid': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_relations_from_or_to_ci
        )

        def __get_merged_relations_outgoing_from_ci(
            self,
            from_ciid,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_relations_outgoing_from_ci  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_relations_outgoing_from_ci(from_ciid, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                from_ciid (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime, none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['from_ciid'] = \
                from_ciid
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_relations_outgoing_from_ci = _Endpoint(
            settings={
                'response_type': ([RelationDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Relation/getMergedRelationsOutgoingFromCI',
                'operation_id': 'get_merged_relations_outgoing_from_ci',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'from_ciid',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'from_ciid',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                    'at_time',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'from_ciid':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime, none_type,),
                },
                'attribute_map': {
                    'from_ciid': 'fromCIID',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'from_ciid': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_relations_outgoing_from_ci
        )

        def __get_merged_relations_with_predicate(
            self,
            predicate_id,
            layer_ids,
            version,
            **kwargs
        ):
            """get_merged_relations_with_predicate  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_merged_relations_with_predicate(predicate_id, layer_ids, version, async_req=True)
            >>> result = thread.get()

            Args:
                predicate_id (str):
                layer_ids ([int]):
                version (str):

            Keyword Args:
                at_time (datetime, none_type): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationDTO]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['predicate_id'] = \
                predicate_id
            kwargs['layer_ids'] = \
                layer_ids
            kwargs['version'] = \
                version
            return self.call_with_http_info(**kwargs)

        self.get_merged_relations_with_predicate = _Endpoint(
            settings={
                'response_type': ([RelationDTO],),
                'auth': [
                    'oauth2',
                    'oauth2'
                ],
                'endpoint_path': '/api/v{version}/Relation/getMergedRelationsWithPredicate',
                'operation_id': 'get_merged_relations_with_predicate',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'predicate_id',
                    'layer_ids',
                    'version',
                    'at_time',
                ],
                'required': [
                    'predicate_id',
                    'layer_ids',
                    'version',
                ],
                'nullable': [
                    'at_time',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'predicate_id':
                        (str,),
                    'layer_ids':
                        ([int],),
                    'version':
                        (str,),
                    'at_time':
                        (datetime, none_type,),
                },
                'attribute_map': {
                    'predicate_id': 'predicateID',
                    'layer_ids': 'layerIDs',
                    'version': 'version',
                    'at_time': 'atTime',
                },
                'location_map': {
                    'predicate_id': 'query',
                    'layer_ids': 'query',
                    'version': 'path',
                    'at_time': 'query',
                },
                'collection_format_map': {
                    'layer_ids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json;odata.metadata=minimal;odata.streaming=true',
                    'application/json;odata.metadata=minimal;odata.streaming=false',
                    'application/json;odata.metadata=minimal',
                    'application/json;odata.metadata=full;odata.streaming=true',
                    'application/json;odata.metadata=full;odata.streaming=false',
                    'application/json;odata.metadata=full',
                    'application/json;odata.metadata=none;odata.streaming=true',
                    'application/json;odata.metadata=none;odata.streaming=false',
                    'application/json;odata.metadata=none',
                    'application/json;odata.streaming=true',
                    'application/json;odata.streaming=false',
                    'application/json',
                    'application/xml',
                    'application/odata',
                    'text/plain',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_merged_relations_with_predicate
        )
