# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import okclient
from okclient.model.inbound_id_method_by_by_union import InboundIDMethodByByUnion
from okclient import configuration


class TestInboundIDMethodByByUnion(unittest.TestCase):
    """InboundIDMethodByByUnion unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
