# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class AbstractInboundIDMethod(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'type',
    ))
    
    
    class type(
        _SchemaTypeChecker(typing.Union[NoneClass, str, ]),
        StrBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[str, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'type':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )

    @classmethod
    @property
    def _discriminator(cls):
        return {
            'type': {
                'InboundIDMethodByAttribute': InboundIDMethodByAttribute,
                'InboundIDMethodByByUnion': InboundIDMethodByByUnion,
                'InboundIDMethodByData': InboundIDMethodByData,
                'InboundIDMethodByIntersect': InboundIDMethodByIntersect,
                'InboundIDMethodByRelatedTempID': InboundIDMethodByRelatedTempID,
                'InboundIDMethodByTemporaryCIID': InboundIDMethodByTemporaryCIID,
                'OKPluginGenericJSONIngest.InboundIDMethodByAttribute, OKPluginGenericJSONIngest': InboundIDMethodByAttribute,
                'OKPluginGenericJSONIngest.InboundIDMethodByByUnion, OKPluginGenericJSONIngest': InboundIDMethodByByUnion,
                'OKPluginGenericJSONIngest.InboundIDMethodByData, OKPluginGenericJSONIngest': InboundIDMethodByData,
                'OKPluginGenericJSONIngest.InboundIDMethodByIntersect, OKPluginGenericJSONIngest': InboundIDMethodByIntersect,
                'OKPluginGenericJSONIngest.InboundIDMethodByRelatedTempID, OKPluginGenericJSONIngest': InboundIDMethodByRelatedTempID,
                'OKPluginGenericJSONIngest.InboundIDMethodByTemporaryCIID, OKPluginGenericJSONIngest': InboundIDMethodByTemporaryCIID,
            }
        }
    _additional_properties = None


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        type: type,
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'AbstractInboundIDMethod':
        return super().__new__(
            cls,
            *args,
            type=type,
            _configuration=_configuration,
        )

from okclient.model.inbound_id_method_by_attribute import InboundIDMethodByAttribute
from okclient.model.inbound_id_method_by_by_union import InboundIDMethodByByUnion
from okclient.model.inbound_id_method_by_data import InboundIDMethodByData
from okclient.model.inbound_id_method_by_intersect import InboundIDMethodByIntersect
from okclient.model.inbound_id_method_by_related_temp_id import InboundIDMethodByRelatedTempID
from okclient.model.inbound_id_method_by_temporary_ciid import InboundIDMethodByTemporaryCIID
