# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class AttributeValueType(
    _SchemaEnumMaker(
        enum_value_to_name={
            "Text": "TEXT",
            "MultilineText": "MULTILINETEXT",
            "Integer": "INTEGER",
            "JSON": "JSON",
            "YAML": "YAML",
            "Image": "IMAGE",
            "Mask": "MASK",
            "Double": "DOUBLE",
            "Boolean": "BOOLEAN",
            "DateTimeWithOffset": "DATETIMEWITHOFFSET",
        }
    ),
    StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    @classmethod
    @property
    def TEXT(cls):
        return cls("Text")
    
    @classmethod
    @property
    def MULTILINETEXT(cls):
        return cls("MultilineText")
    
    @classmethod
    @property
    def INTEGER(cls):
        return cls("Integer")
    
    @classmethod
    @property
    def JSON(cls):
        return cls("JSON")
    
    @classmethod
    @property
    def YAML(cls):
        return cls("YAML")
    
    @classmethod
    @property
    def IMAGE(cls):
        return cls("Image")
    
    @classmethod
    @property
    def MASK(cls):
        return cls("Mask")
    
    @classmethod
    @property
    def DOUBLE(cls):
        return cls("Double")
    
    @classmethod
    @property
    def BOOLEAN(cls):
        return cls("Boolean")
    
    @classmethod
    @property
    def DATETIMEWITHOFFSET(cls):
        return cls("DateTimeWithOffset")
