# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class GenericInboundCI(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    tempID = StrSchema
    
    
    class idMethod(
        ComposedSchema
    ):
    
        @classmethod
        @property
        @functools.cache
        def _composed_schemas(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return {
                'allOf': [
                ],
                'oneOf': [
                    InboundIDMethodByData,
                    InboundIDMethodByAttributeModifiers,
                    InboundIDMethodByAttribute,
                    InboundIDMethodByRelatedTempID,
                    InboundIDMethodByTemporaryCIID,
                    InboundIDMethodByByUnion,
                    InboundIDMethodByIntersect,
                ],
                'anyOf': [
                ],
                'not':
                    None
            }
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, str, date, datetime, int, float, decimal.Decimal, None, list, tuple, bytes],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'idMethod':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )

    @classmethod
    @property
    def sameTempIDHandling(cls) -> typing.Type['SameTempIDHandling']:
        return SameTempIDHandling

    @classmethod
    @property
    def sameTargetCIHandling(cls) -> typing.Type['SameTargetCIHandling']:
        return SameTargetCIHandling

    @classmethod
    @property
    def noFoundTargetCIHandling(cls) -> typing.Type['NoFoundTargetCIHandling']:
        return NoFoundTargetCIHandling
    
    
    class attributes(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['GenericInboundAttribute']:
            return GenericInboundAttribute


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        tempID: typing.Union[tempID, Unset] = unset,
        idMethod: typing.Union[idMethod, Unset] = unset,
        sameTempIDHandling: typing.Union['SameTempIDHandling', Unset] = unset,
        sameTargetCIHandling: typing.Union['SameTargetCIHandling', Unset] = unset,
        noFoundTargetCIHandling: typing.Union['NoFoundTargetCIHandling', Unset] = unset,
        attributes: typing.Union[attributes, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'GenericInboundCI':
        return super().__new__(
            cls,
            *args,
            tempID=tempID,
            idMethod=idMethod,
            sameTempIDHandling=sameTempIDHandling,
            sameTargetCIHandling=sameTargetCIHandling,
            noFoundTargetCIHandling=noFoundTargetCIHandling,
            attributes=attributes,
            _configuration=_configuration,
            **kwargs,
        )

from okclient.model.generic_inbound_attribute import GenericInboundAttribute
from okclient.model.inbound_id_method_by_attribute import InboundIDMethodByAttribute
from okclient.model.inbound_id_method_by_attribute_modifiers import InboundIDMethodByAttributeModifiers
from okclient.model.inbound_id_method_by_by_union import InboundIDMethodByByUnion
from okclient.model.inbound_id_method_by_data import InboundIDMethodByData
from okclient.model.inbound_id_method_by_intersect import InboundIDMethodByIntersect
from okclient.model.inbound_id_method_by_related_temp_id import InboundIDMethodByRelatedTempID
from okclient.model.inbound_id_method_by_temporary_ciid import InboundIDMethodByTemporaryCIID
from okclient.model.no_found_target_ci_handling import NoFoundTargetCIHandling
from okclient.model.same_target_ci_handling import SameTargetCIHandling
from okclient.model.same_temp_id_handling import SameTempIDHandling
