# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IEdmModel(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class schemaElements(
        _SchemaTypeChecker(typing.Union[tuple, none_type, ]),
        ListBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[list, tuple, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'schemaElements':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class vocabularyAnnotations(
        _SchemaTypeChecker(typing.Union[tuple, none_type, ]),
        ListBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[list, tuple, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'vocabularyAnnotations':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class referencedModels(
        _SchemaTypeChecker(typing.Union[tuple, none_type, ]),
        ListBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[list, tuple, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'referencedModels':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class declaredNamespaces(
        _SchemaTypeChecker(typing.Union[tuple, none_type, ]),
        ListBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[list, tuple, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'declaredNamespaces':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    directValueAnnotationsManager = DictSchema

    @classmethod
    @property
    def entityContainer(cls) -> typing.Type['IEdmEntityContainer']:
        return IEdmEntityContainer


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        schemaElements: typing.Union[schemaElements, Unset] = unset,
        vocabularyAnnotations: typing.Union[vocabularyAnnotations, Unset] = unset,
        referencedModels: typing.Union[referencedModels, Unset] = unset,
        declaredNamespaces: typing.Union[declaredNamespaces, Unset] = unset,
        directValueAnnotationsManager: typing.Union[directValueAnnotationsManager, Unset] = unset,
        entityContainer: typing.Union['IEdmEntityContainer', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IEdmModel':
        return super().__new__(
            cls,
            *args,
            schemaElements=schemaElements,
            vocabularyAnnotations=vocabularyAnnotations,
            referencedModels=referencedModels,
            declaredNamespaces=declaredNamespaces,
            directValueAnnotationsManager=directValueAnnotationsManager,
            entityContainer=entityContainer,
            _configuration=_configuration,
            **kwargs,
        )

from okclient.model.i_edm_entity_container import IEdmEntityContainer
from okclient.model.i_edm_schema_element import IEdmSchemaElement
from okclient.model.i_edm_vocabulary_annotation import IEdmVocabularyAnnotation
