# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class InboundIDMethodByAttribute(
    ComposedBase,
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def attribute(cls) -> typing.Type['GenericInboundAttribute']:
        return GenericInboundAttribute

    @classmethod
    @property
    def modifiers(cls) -> typing.Type['InboundIDMethodByAttributeModifiers']:
        return InboundIDMethodByAttributeModifiers

    @classmethod
    @property
    def _discriminator(cls):
        return {
            'type': {
                'OKPluginGenericJSONIngest.InboundIDMethodByAttribute, OKPluginGenericJSONIngest': InboundIDMethodByAttribute,
                'OKPluginGenericJSONIngest.InboundIDMethodByByUnion, OKPluginGenericJSONIngest': InboundIDMethodByByUnion,
                'OKPluginGenericJSONIngest.InboundIDMethodByData, OKPluginGenericJSONIngest': InboundIDMethodByData,
                'OKPluginGenericJSONIngest.InboundIDMethodByIntersect, OKPluginGenericJSONIngest': InboundIDMethodByIntersect,
                'OKPluginGenericJSONIngest.InboundIDMethodByRelatedTempID, OKPluginGenericJSONIngest': InboundIDMethodByRelatedTempID,
                'OKPluginGenericJSONIngest.InboundIDMethodByTemporaryCIID, OKPluginGenericJSONIngest': InboundIDMethodByTemporaryCIID,
            }
        }
    _additional_properties = None

    @classmethod
    @property
    @functools.cache
    def _composed_schemas(cls):
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        return {
            'allOf': [
                AbstractInboundIDMethod,
            ],
            'oneOf': [
            ],
            'anyOf': [
            ],
            'not':
                None
        }

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        attribute: typing.Union['GenericInboundAttribute', Unset] = unset,
        modifiers: typing.Union['InboundIDMethodByAttributeModifiers', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
    ) -> 'InboundIDMethodByAttribute':
        return super().__new__(
            cls,
            *args,
            attribute=attribute,
            modifiers=modifiers,
            _configuration=_configuration,
        )

from okclient.model.abstract_inbound_id_method import AbstractInboundIDMethod
from okclient.model.generic_inbound_attribute import GenericInboundAttribute
from okclient.model.inbound_id_method_by_attribute import InboundIDMethodByAttribute
from okclient.model.inbound_id_method_by_attribute_modifiers import InboundIDMethodByAttributeModifiers
from okclient.model.inbound_id_method_by_by_union import InboundIDMethodByByUnion
from okclient.model.inbound_id_method_by_data import InboundIDMethodByData
from okclient.model.inbound_id_method_by_intersect import InboundIDMethodByIntersect
from okclient.model.inbound_id_method_by_related_temp_id import InboundIDMethodByRelatedTempID
from okclient.model.inbound_id_method_by_temporary_ciid import InboundIDMethodByTemporaryCIID
