# coding: utf-8

"""
    Landscape omnikeeper REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class ProblemDetails(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class type(
        _SchemaTypeChecker(typing.Union[NoneClass, str, ]),
        StrBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[str, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'type':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class title(
        _SchemaTypeChecker(typing.Union[NoneClass, str, ]),
        StrBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[str, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'title':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class status(
        _SchemaTypeChecker(typing.Union[NoneClass, decimal.Decimal, ]),
        Int32Base,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'status':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class detail(
        _SchemaTypeChecker(typing.Union[NoneClass, str, ]),
        StrBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[str, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'detail':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )
    
    
    class instance(
        _SchemaTypeChecker(typing.Union[NoneClass, str, ]),
        StrBase,
        NoneBase,
        Schema
    ):
    
        def __new__(
            cls,
            *args: typing.Union[str, None, ],
            _configuration: typing.Optional[Configuration] = None,
        ) -> 'instance':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
            )


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        type: typing.Union[type, Unset] = unset,
        title: typing.Union[title, Unset] = unset,
        status: typing.Union[status, Unset] = unset,
        detail: typing.Union[detail, Unset] = unset,
        instance: typing.Union[instance, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'ProblemDetails':
        return super().__new__(
            cls,
            *args,
            type=type,
            title=title,
            status=status,
            detail=detail,
            instance=instance,
            _configuration=_configuration,
            **kwargs,
        )
