# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import re  # noqa: F401
import sys  # noqa: F401
import typing
import urllib3
import functools  # noqa: F401
from urllib3._collections import HTTPHeaderDict

from okclient import api_client, exceptions
import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)

from okclient.model.problem_details import ProblemDetails
from okclient.model.change_data_request import ChangeDataRequest

# path params
ContextSchema = StrSchema
VersionSchema = StrSchema
RequestRequiredPathParams = typing.TypedDict(
    'RequestRequiredPathParams',
    {
        'context': ContextSchema,
        'version': VersionSchema,
    }
)
RequestOptionalPathParams = typing.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_context = api_client.PathParameter(
    name="context",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ContextSchema,
    required=True,
)
request_path_version = api_client.PathParameter(
    name="version",
    style=api_client.ParameterStyle.SIMPLE,
    schema=VersionSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadataminimal = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatafull = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataMetadatanone = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataStreamingtrue = ChangeDataRequest
SchemaForRequestBodyApplicationJsonodataStreamingfalse = ChangeDataRequest
SchemaForRequestBodyApplicationXml = ChangeDataRequest
SchemaForRequestBodyTextPlain = ChangeDataRequest
SchemaForRequestBodyTextJson = ChangeDataRequest
SchemaForRequestBodyApplicationJson = ChangeDataRequest


request_body_change_data_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
        'application/json;odata.metadata=minimal;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue),
        'application/json;odata.metadata=minimal;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse),
        'application/json;odata.metadata=minimal': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimal),
        'application/json;odata.metadata=full;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue),
        'application/json;odata.metadata=full;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse),
        'application/json;odata.metadata=full': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafull),
        'application/json;odata.metadata=none;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue),
        'application/json;odata.metadata=none;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse),
        'application/json;odata.metadata=none': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanone),
        'application/json;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataStreamingtrue),
        'application/json;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataStreamingfalse),
        'application/xml': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationXml),
        'text/plain': api_client.MediaType(
            schema=SchemaForRequestBodyTextPlain),
        'text/json': api_client.MediaType(
            schema=SchemaForRequestBodyTextJson),
        'application/*+json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_path = '/api/v{version}/GridView/contexts/{context}/change'
_method = 'POST'
_auth = [
    'oauth2',
    'oauth2',
]


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: Unset = unset
    headers: Unset = unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
)
SchemaFor400ResponseBodyApplicationJson = ProblemDetails
SchemaFor400ResponseBodyApplicationXml = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadataminimal = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatafull = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataMetadatanone = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataStreamingtrue = ProblemDetails
SchemaFor400ResponseBodyApplicationJsonodataStreamingfalse = ProblemDetails
SchemaFor400ResponseBodyTextPlain = ProblemDetails
SchemaFor400ResponseBodyApplicationOctetStream = ProblemDetails
SchemaFor400ResponseBodyTextJson = ProblemDetails


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor400ResponseBodyApplicationJson,
        SchemaFor400ResponseBodyApplicationXml,
        SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue,
        SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse,
        SchemaFor400ResponseBodyApplicationJsonodataMetadataminimal,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatafull,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse,
        SchemaFor400ResponseBodyApplicationJsonodataMetadatanone,
        SchemaFor400ResponseBodyApplicationJsonodataStreamingtrue,
        SchemaFor400ResponseBodyApplicationJsonodataStreamingfalse,
        SchemaFor400ResponseBodyTextPlain,
        SchemaFor400ResponseBodyApplicationOctetStream,
        SchemaFor400ResponseBodyTextJson,
    ]
    headers: Unset = unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationXml),
        'application/json;odata.metadata=minimal;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue),
        'application/json;odata.metadata=minimal;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse),
        'application/json;odata.metadata=minimal': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadataminimal),
        'application/json;odata.metadata=full;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue),
        'application/json;odata.metadata=full;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse),
        'application/json;odata.metadata=full': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatafull),
        'application/json;odata.metadata=none;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue),
        'application/json;odata.metadata=none;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse),
        'application/json;odata.metadata=none': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataMetadatanone),
        'application/json;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataStreamingtrue),
        'application/json;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJsonodataStreamingfalse),
        'text/plain': api_client.MediaType(
            schema=SchemaFor400ResponseBodyTextPlain),
        'application/octet-stream': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationOctetStream),
        'text/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyTextJson),
    },
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: Unset = unset
    headers: Unset = unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '404': _response_for_404,
}
_all_accept_content_types = (
    'application/json',
    'application/xml',
    'application/json;odata.metadata=minimal;odata.streaming=true',
    'application/json;odata.metadata=minimal;odata.streaming=false',
    'application/json;odata.metadata=minimal',
    'application/json;odata.metadata=full;odata.streaming=true',
    'application/json;odata.metadata=full;odata.streaming=false',
    'application/json;odata.metadata=full',
    'application/json;odata.metadata=none;odata.streaming=true',
    'application/json;odata.metadata=none;odata.streaming=false',
    'application/json;odata.metadata=none',
    'application/json;odata.streaming=true',
    'application/json;odata.streaming=false',
    'text/plain',
    'application/octet-stream',
    'text/json',
)


class GridViewChangeData(api_client.Api):

    def grid_view_change_data(
        self: api_client.Api,
        body: typing.Union[SchemaForRequestBodyApplicationJson, SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadataminimal, SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadatafull, SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadatanone, SchemaForRequestBodyApplicationJsonodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataStreamingfalse, SchemaForRequestBodyApplicationXml, SchemaForRequestBodyTextPlain, SchemaForRequestBodyTextJson, SchemaForRequestBodyApplicationJson, Unset] = unset,
        path_params: RequestPathParams = frozendict(),
        content_type: str = 'application/json',
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        Saves grid view row changes and returns change results
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs(RequestPathParams, path_params)
        used_path = _path

        _path_params = {}
        for parameter in (
            request_path_context,
            request_path_version,
        ):
            parameter_data = path_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)

        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        _fields = None
        _body = None
        if body is not unset:
            serialized_data = request_body_change_data_request.serialize(body, content_type)
            _headers.add('Content-Type', content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
        response = self.api_client.call_api(
            resource_path=used_path,
            method=_method,
            headers=_headers,
            fields=_fields,
            body=_body,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response
