# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import re  # noqa: F401
import sys  # noqa: F401
import typing
import urllib3
import functools  # noqa: F401
from urllib3._collections import HTTPHeaderDict

from okclient import api_client, exceptions
import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)

from okclient.model.o_data_service_document import ODataServiceDocument

# path params
ContextSchema = StrSchema
RequestRequiredPathParams = typing.TypedDict(
    'RequestRequiredPathParams',
    {
        'context': ContextSchema,
    }
)
RequestOptionalPathParams = typing.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_context = api_client.PathParameter(
    name="context",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ContextSchema,
    required=True,
)
_path = '/api/odata/{context}'
_method = 'GET'
_auth = [
    'oauth2',
    'oauth2',
]
SchemaFor200ResponseBodyApplicationJson = ODataServiceDocument
SchemaFor200ResponseBodyApplicationXml = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatafull = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataMetadatanone = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue = ODataServiceDocument
SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse = ODataServiceDocument
SchemaFor200ResponseBodyTextPlain = ODataServiceDocument
SchemaFor200ResponseBodyApplicationOctetStream = ODataServiceDocument
SchemaFor200ResponseBodyTextJson = ODataServiceDocument


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor200ResponseBodyApplicationJson,
        SchemaFor200ResponseBodyApplicationXml,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatafull,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse,
        SchemaFor200ResponseBodyApplicationJsonodataMetadatanone,
        SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue,
        SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse,
        SchemaFor200ResponseBodyTextPlain,
        SchemaFor200ResponseBodyApplicationOctetStream,
        SchemaFor200ResponseBodyTextJson,
    ]
    headers: Unset = unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationXml),
        'application/json;odata.metadata=minimal;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingtrue),
        'application/json;odata.metadata=minimal;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimalodataStreamingfalse),
        'application/json;odata.metadata=minimal': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadataminimal),
        'application/json;odata.metadata=full;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingtrue),
        'application/json;odata.metadata=full;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafullodataStreamingfalse),
        'application/json;odata.metadata=full': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatafull),
        'application/json;odata.metadata=none;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingtrue),
        'application/json;odata.metadata=none;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanoneodataStreamingfalse),
        'application/json;odata.metadata=none': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataMetadatanone),
        'application/json;odata.streaming=true': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataStreamingtrue),
        'application/json;odata.streaming=false': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJsonodataStreamingfalse),
        'text/plain': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextPlain),
        'application/octet-stream': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationOctetStream),
        'text/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
    'application/xml',
    'application/json;odata.metadata=minimal;odata.streaming=true',
    'application/json;odata.metadata=minimal;odata.streaming=false',
    'application/json;odata.metadata=minimal',
    'application/json;odata.metadata=full;odata.streaming=true',
    'application/json;odata.metadata=full;odata.streaming=false',
    'application/json;odata.metadata=full',
    'application/json;odata.metadata=none;odata.streaming=true',
    'application/json;odata.metadata=none;odata.streaming=false',
    'application/json;odata.metadata=none',
    'application/json;odata.streaming=true',
    'application/json;odata.streaming=false',
    'text/plain',
    'application/octet-stream',
    'text/json',
)


class MetadataGetServiceDocument(api_client.Api):

    def metadata_get_service_document(
        self: api_client.Api,
        path_params: RequestPathParams = frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs(RequestPathParams, path_params)
        used_path = _path

        _path_params = {}
        for parameter in (
            request_path_context,
        ):
            parameter_data = path_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)

        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        response = self.api_client.call_api(
            resource_path=used_path,
            method=_method,
            headers=_headers,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response
