# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import re  # noqa: F401
import sys  # noqa: F401
import typing
import urllib3
import functools  # noqa: F401
from urllib3._collections import HTTPHeaderDict

from okclient import api_client, exceptions
import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from okclient.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)

from okclient.model.ansible_inventory_scan_dto import AnsibleInventoryScanDTO

# query params
WriteLayerIDSchema = StrSchema


class SearchLayerIDsSchema(
    ListSchema
):
    _items = StrSchema
RequestRequiredQueryParams = typing.TypedDict(
    'RequestRequiredQueryParams',
    {
        'writeLayerID': WriteLayerIDSchema,
        'searchLayerIDs': SearchLayerIDsSchema,
    }
)
RequestOptionalQueryParams = typing.TypedDict(
    'RequestOptionalQueryParams',
    {
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_write_layer_id = api_client.QueryParameter(
    name="writeLayerID",
    style=api_client.ParameterStyle.FORM,
    schema=WriteLayerIDSchema,
    required=True,
    explode=True,
)
request_query_search_layer_ids = api_client.QueryParameter(
    name="searchLayerIDs",
    style=api_client.ParameterStyle.FORM,
    schema=SearchLayerIDsSchema,
    required=True,
    explode=True,
)
# path params
VersionSchema = StrSchema
RequestRequiredPathParams = typing.TypedDict(
    'RequestRequiredPathParams',
    {
        'version': VersionSchema,
    }
)
RequestOptionalPathParams = typing.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_version = api_client.PathParameter(
    name="version",
    style=api_client.ParameterStyle.SIMPLE,
    schema=VersionSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadataminimal = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatafull = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataMetadatanone = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataStreamingtrue = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJsonodataStreamingfalse = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationXml = AnsibleInventoryScanDTO
SchemaForRequestBodyTextPlain = AnsibleInventoryScanDTO
SchemaForRequestBodyTextJson = AnsibleInventoryScanDTO
SchemaForRequestBodyApplicationJson = AnsibleInventoryScanDTO


request_body_ansible_inventory_scan_dto = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
        'application/json;odata.metadata=minimal;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue),
        'application/json;odata.metadata=minimal;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse),
        'application/json;odata.metadata=minimal': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadataminimal),
        'application/json;odata.metadata=full;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue),
        'application/json;odata.metadata=full;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse),
        'application/json;odata.metadata=full': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatafull),
        'application/json;odata.metadata=none;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue),
        'application/json;odata.metadata=none;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse),
        'application/json;odata.metadata=none': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataMetadatanone),
        'application/json;odata.streaming=true': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataStreamingtrue),
        'application/json;odata.streaming=false': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJsonodataStreamingfalse),
        'application/xml': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationXml),
        'text/plain': api_client.MediaType(
            schema=SchemaForRequestBodyTextPlain),
        'text/json': api_client.MediaType(
            schema=SchemaForRequestBodyTextJson),
        'application/*+json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_path = '/api/v{version}/Ingest/AnsibleInventoryScan'
_method = 'POST'
_auth = [
    'oauth2',
    'oauth2',
]


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: Unset = unset
    headers: Unset = unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
)
_status_code_to_response = {
    '200': _response_for_200,
}


class AnsibleInventoryScanIngestIngestAnsibleInventoryScan(api_client.Api):

    def ansible_inventory_scan_ingest_ingest_ansible_inventory_scan(
        self: api_client.Api,
        body: typing.Union[SchemaForRequestBodyApplicationJson, SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadataminimalodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadataminimal, SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadatafullodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadatafull, SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataMetadatanoneodataStreamingfalse, SchemaForRequestBodyApplicationJsonodataMetadatanone, SchemaForRequestBodyApplicationJsonodataStreamingtrue, SchemaForRequestBodyApplicationJsonodataStreamingfalse, SchemaForRequestBodyApplicationXml, SchemaForRequestBodyTextPlain, SchemaForRequestBodyTextJson, SchemaForRequestBodyApplicationJson],
        query_params: RequestQueryParams = frozendict(),
        path_params: RequestPathParams = frozendict(),
        content_type: str = 'application/json',
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs(RequestPathParams, path_params)
        used_path = _path

        _path_params = {}
        for parameter in (
            request_path_version,
        ):
            parameter_data = path_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)

        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)

        prefix_separator_iterator = None
        for parameter in (
            request_query_write_layer_id,
            request_query_search_layer_ids,
        ):
            parameter_data = query_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value

        _headers = HTTPHeaderDict()
        # TODO add cookie handling

        if body is unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        serialized_data = request_body_ansible_inventory_scan_dto.serialize(body, content_type)
        _headers.add('Content-Type', content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
        response = self.api_client.call_api(
            resource_path=used_path,
            method=_method,
            headers=_headers,
            fields=_fields,
            body=_body,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response
